// Package openapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen DO NOT EDIT.
package openapi

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
)

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/4STz44TMQzGXyUyHIfOQOEyJyohwSLteQ+Ig5txd7IktklcoFrNu6NM6Z/dFriMkskX",
	"+/Mv9iN4SSpMbAX6Ryh+pITzcqV6S4YDGtatZlHKFmg+HKj4HNSCcN3aTgl6KJYD38PUQMRiXlIKVka8",
	"qvhBuVy/PTWQ6fs2ZBqg/3IUNk+SPk/xtTmEkfUDeYOpxgm8kZrBCxt6q0tKGCL0wPIqk8bd+w1+o0ES",
	"Bl54SdAAY6pxPsvI7oNQNWvBYv13u3N3tHYrVTirAF4vukVXdaLEqAF6WC66xRIaULRxJtbWzz3NHipJ",
	"rGXcDNDDRzKoJRcVLnu8b7ruYJt4vmL0y1qNGPj0TNfYTU8x9bByJSSN5PYSd8hTtVMD7UgYbfyXuU97",
	"xYXFtxeNADc8BI9GzkZyP2ntUNWF4o4xMVZM77rl5d27k3zLA2VXn8SIkf3RbDpryL/ZPTbtf5miaqx2",
	"g3D7UOQZ2ZeZNtDDi/Y0Ie2f8WjPZ+MK88OZw7Vs7RzGXMg0/Q4AAP//oD+MBXcDAAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %s", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	var res = make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.Swagger, err error) {
	var resolvePath = PathToRawSpec("")

	loader := openapi3.NewSwaggerLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.SwaggerLoader, url *url.URL) ([]byte, error) {
		var pathToFile = url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadSwaggerFromData(specData)
	if err != nil {
		return
	}
	return
}
