// Package openapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen DO NOT EDIT.
package openapi

// AppMetadata defines model for AppMetadata.
type AppMetadata struct {
	Description   string `json:"description"`
	Lastcommitsha string `json:"lastcommitsha"`
	Version       string `json:"version"`
}
