name: Build and deploy
on:
  push:
    branches:
      - master
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Set up Go env
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Test
        run: make test
      
      - name: Deploy
        run: make deploy
